version: "3.3"
services:
  mebrak:
    image: "darakeon/mebrak"
    container_name: mebrak
  dfm:
    image: "darakeon/dfm"
    container_name: dfm
    volumes:
      - "/var/cfg/dfm:/var/cfg"
      - "/var/data/dfm:/var/www/data"
  nginx:
    image: "darakeon/server"
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/data/letsencrypt:/etc/letsencrypt"
    depends_on:
      - "dfm"
      - "mebrak"
