version: "3.3"
services:
  mysql:
    image: "mysql"
    container_name: mysql
    ports:
      - "2021:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
  mebrak:
    image: "darakeon/mebrak"
    container_name: mebrak
  dfm:
    image: "darakeon/dfm"
    container_name: dfm
    volumes:
      - "/var/cfg/dfm:/var/cfg"
  nginx:
    image: "darakeon/server"
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/data/letsencrypt:/etc/letsencrypt"
