version: 2.1

jobs:
  trufflehog:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: install trufflehog
          command: apk add --no-cache git && pip install gitdb2==3.0.0 trufflehog
      - run:
          name: run trufflehog
          command: trufflehog --exclude_paths trufflehog/exclude-patterns.txt --allow trufflehog/allow.json .

  docker:
    docker:
      - image: darakeon/dockery
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: Build and Push Alpine
          path: docker
          command: make alpine_push
      - run:
          name: Build and Push Ubuntu
          path: docker
          command: make ubuntu_push
      - run:
          name: Build and Push Dockery
          path: docker
          command: make dockery_push
      - run:
          name: Build and Push Netcore Alpine
          path: docker
          command: make netcore_alpine_push
      - run:
          name: Build and Push Netcore Ubuntu
          path: docker
          command: make netcore_ubuntu_push
      - run:
          name: Build and Push Netcore Libman Alpine
          path: docker
          command: make netcore_alpine_libman_push
      - run:
          name: Build and Push Netcore Libman Ubuntu
          path: docker
          command: make netcore_libman_ubuntu_push
      - run:
          name: Build and Push Netcore Server
          path: docker
          command: make netcore_server_push
      - run:
          name: Build and Push Server
          path: docker
          command: make server_push

workflows:
  deploy:
    jobs:
      - trufflehog
      - docker:
          filters:
            branches:
              only: main
          requires:
            - trufflehog
