#!/bin/sh
set -e

chmod -R 755 /var/lib/nginx

if [ ! -e /etc/letsencrypt/options-ssl-nginx.conf ]; then
    mv /etc/nginx/conf.d/ /etc/nginx/conf.d+wait/;
    #certbot certonly -n -m $CERTBOT_EMAIL --nginx --agree-tos -d darakeon.com;
    #certbot certonly -n -m $CERTBOT_EMAIL --nginx --agree-tos -d observe.darakeon.com;
    certbot certonly -n -m $CERTBOT_EMAIL --nginx --agree-tos -d dontflymoney.com;
    certbot certonly -n -m $CERTBOT_EMAIL --nginx --agree-tos -d api.dontflymoney.com;
    certbot certonly -n -m $CERTBOT_EMAIL --nginx --agree-tos -d midna.dontflymoney.com;
    #certbot certonly -n -m $CERTBOT_EMAIL --nginx --agree-tos -d meak.com.br;
    mv /etc/nginx/conf.d+wait/ /etc/nginx/conf.d/;
fi

nginx -g "daemon off;" &

./TLS || echo 'TLS DID NOT RUN'

tail -f /dev/null
