version: "3.9"
services:
  robot_wipe:
    image: "darakeon/dfm-robot"
    container_name: robot_wipe
    volumes:
      - "/var/cfg/dfm:/var/cfg"
      - "/var/data/dfm/robot-wipe:/var/robot/data"
      - "/var/data/dfm/nh:/var/logs/dfm/nh"
    environment:
      - TASK=2
    deploy:
      resources:
          limits:
            cpus: 0.2
            memory: 200M
