version: "3.9"
services:
  robot_schedules:
    image: "darakeon/dfm-robot"
    container_name: robot_schedules
    volumes:
      - "/var/cfg/dfm:/var/cfg"
      - "/var/data/dfm/robot-schedules:/var/robot/data"
      - "/var/data/dfm/nh:/var/logs/dfm/nh"
    environment:
      - TASK=schedules
    deploy:
      resources:
          limits:
            cpus: 0.01
            memory: 100M
