services:

  mebrak:
    image: darakeon/mebrak
    container_name: mebrak
    deploy:
      resources:
          limits:
            cpus: 0.01
            memory: 150M
    #restart: on-failure:3
    #healthcheck:
    #  test: ["CMD", "curl", "-k", "https://localhost:2703"]
    #  start_period: 60s
    #  timeout: 60s
    #  retries: 2

  dfm:
    image: darakeon/dfm-site
    container_name: dfm
    volumes:
      - /var/cfg/dfm:/var/cfg
      - /var/data/dfm/mvc:/var/www/data
      - /var/data/dfm/nh:/var/logs/dfm/nh
    deploy:
      resources:
          limits:
            cpus: 0.01
            memory: 200M
    #restart: on-failure:3
    #healthcheck:
    #  test: ["CMD", "curl", "-k", "https://localhost:2011/contract"]
    #  start_period: 60s
    #  timeout: 60s
    #  retries: 2

  dfm-api:
    image: darakeon/dfm-api
    container_name: dfm-api
    volumes:
      - /var/cfg/dfm:/var/cfg
      - /var/data/dfm/api:/var/www/data
      - /var/data/dfm/nh-api:/var/logs/dfm/nh
    deploy:
      resources:
          limits:
            cpus: 0.01
            memory: 200M
    #restart: on-failure:3
    #healthcheck:
    #  test: ["CMD", "curl", "-k", "https://localhost:2023"]
    #  start_period: 60s
    #  timeout: 60s
    #  retries: 2

  dfm-sql-runner:
    image: darakeon/sql-runner
    container_name: sql-runner
    env_file:
      - /var/cfg/sql-runner/.env
    deploy:
      resources:
          limits:
            cpus: 0.01
            memory: 100M

  midna:
    image: darakeon/dfm-midna
    container_name: midna
    volumes:
      - /var/cfg/midna:/var/midna/config
      - /var/data/midna/log:/var/log/gunicorn # access.log + error.log
      - /var/data/midna/run:/var/run/gunicorn # prod.pid
      - /var/data/midna/static:/var/midna/static/outside
    env_file:
      - /var/cfg/midna/prod.env
    deploy:
      resources:
          limits:
            cpus: 0.01
            memory: 100M
    #restart: on-failure:3
    #healthcheck:
    #  test: ["CMD", "curl", "http://localhost:8627"]
    #  start_period: 60s
    #  timeout: 60s
    #  retries: 2

  curriculum:
    image: darakeon/curriculum
    container_name: curriculum
    deploy:
      resources:
          limits:
            cpus: 0.01
            memory: 100M
    #restart: on-failure:3
    #healthcheck:
    #  test: ["CMD", "curl", "http://curriculum:3000"]
    #  start_period: 60s
    #  timeout: 60s
    #  retries: 2

  nginx:
    image: darakeon/server
    container_name: server
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/data/letsencrypt:/etc/letsencrypt
      - /var/data/nginx/log:/var/log/nginx/
      - /var/data/midna/static:/var/midna/static/outside
    depends_on:
      - dfm
      - mebrak
      - curriculum
      - midna
      - dfm-api
    deploy:
      resources:
          limits:
            cpus: 0.01
            memory: 100M

  #prometheus:
  #  image: prom/prometheus
  #  container_name: prometheus
  #  volumes:
  #    - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #    - /var/data/prometheus:/prometheus
  #  depends_on:
  #    - dfm
  #    - mebrak
  #  deploy:
  #    resources:
  #        limits:
  #          cpus: 0.01
  #          memory: 100M

  #grafana:
  #  image: grafana/grafana
  #  container_name: grafana
  #  volumes:
  #    - ../grafana/custom.ini:/usr/share/grafana/conf/custom.ini
  #    - ../grafana/provisioning/:/etc/grafana/provisioning/
  #    - /var/data/grafana/log:/var/log/grafana
  #    - /var/data/grafana/configs:/var/lib/grafana
  #  environment:
  #    - GF_SECURITY_ADMIN_USER=$GF_SECURITY_ADMIN_USER
  #    - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
  #    - GF_SERVER_HTTP_PORT=3030
  #  depends_on:
  #    - prometheus
  #  deploy:
  #    resources:
  #        limits:
  #          cpus: 0.01
  #          memory: 100M
