version: "3.9"

services:

  mebrak:
    image: "darakeon/mebrak"
    container_name: mebrak

  dfm:
    image: "darakeon/dfm-site"
    container_name: dfm
    volumes:
      - "/var/cfg/dfm:/var/cfg"
      - "/var/data/dfm/mvc:/var/www/data"
      - "/var/data/dfm/nh:/var/logs/dfm/nh"

  curriculum:
    image: "darakeon/curriculum"
    container_name: curriculum

  nginx:
    image: "darakeon/server"
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/data/letsencrypt:/etc/letsencrypt"
      - "/var/data/log_nginx:/var/log/nginx/"
    depends_on:
      - "dfm"
      - "mebrak"
      - "curriculum"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/data/prometheus:/prometheus
    depends_on:
      - "dfm"
      - "mebrak"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ../grafana/custom.ini:/usr/share/grafana/conf/custom.ini
      - ../grafana/provisioning/:/etc/grafana/provisioning/
      - /var/data/grafana/log:/var/log/grafana
      - /var/data/grafana/configs:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=$GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
      - GF_SERVER_HTTP_PORT=3030
    depends_on:
      - prometheus
