version: "3.9"
services:
  mebrak:
    image: "darakeon/mebrak"
    container_name: mebrak
  dfm:
    image: "darakeon/dfm-site"
    container_name: dfm
    volumes:
      - "/var/cfg/dfm:/var/cfg"
      - "/var/data/dfm/mvc:/var/www/data"
      - "/var/data/dfm/nh:/var/logs/dfm/nh"
  curriculum:
    image: "darakeon/curriculum"
    container_name: curriculum
  nginx:
    image: "darakeon/server"
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/data/letsencrypt:/etc/letsencrypt"
    depends_on:
      - "dfm"
      - "mebrak"
      - "curriculum"
